/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RoundPanel.java
 *
 * Created on Mar 3, 2010, 9:46:24 AM
 */

/**
 *
 * @author Administrator
 */

import javax.swing.*;
import java.awt.*;

public class RoundPanel extends javax.swing.JPanel {

    VisualizationPanel viz = new VisualizationPanel();
    int roundNum;
    BitList L, R, K, expandedList, firstXorList, sBoxesList, permutedList, secondXorList;

    /** Creates new form RoundPanel */
    public RoundPanel(int x, BitList L, BitList R, BitList K) {
        this.L = L;
        this.R = R;
        this.K = K;
        initComponents();
        customGUI();
    }

    public RoundPanel() {
        initComponents();
        customGUI();       
    }

    private void customGUI(){
		JPanel linePanel = new LinePanel(0, 0, 0, 70);
		linePanel.setLocation(415, 80);
		linePanel.setSize(10, 100);
		linePanel.setVisible(true);
		this.add(linePanel);
                JPanel longlinePanel = new LinePanel(0, 0, 0, 325);
		longlinePanel.setLocation(300, 160);
		longlinePanel.setSize(1, 325);
		longlinePanel.setVisible(true);
		this.add(longlinePanel);
                JPanel horzlinePanel = new LinePanel(0, 0, 50, 0);
		horzlinePanel.setLocation(270, 160);
		horzlinePanel.setSize(50, 1);
		horzlinePanel.setVisible(true);
		this.add(horzlinePanel);
                JPanel horzlinePanel2 = new LinePanel(0, 0, 50, 0);
		horzlinePanel2.setLocation(300, 485);
		horzlinePanel2.setSize(50, 1);
		horzlinePanel2.setVisible(true);
		this.add(horzlinePanel2);
                JPanel horzlinePanel3 = new LinePanel(0, 0, 50, 0);
		horzlinePanel3.setLocation(10, 70);
		horzlinePanel3.setSize(50, 1);
		horzlinePanel3.setVisible(true);
		this.add(horzlinePanel3);
                JPanel leftLinePanel = new LinePanel(0, 0, 0, 500);
		leftLinePanel.setLocation(10, 70);
		leftLinePanel.setSize(1, 375);
		leftLinePanel.setVisible(true);
		this.add(leftLinePanel);
                JPanel horzlinePanel4 = new LinePanel(0, 0, 270, 0);
		horzlinePanel4.setLocation(10, 445);
		horzlinePanel4.setSize(270, 1);
		horzlinePanel4.setVisible(true);
		this.add(horzlinePanel4);
                JPanel diaglinePanel = new LinePanel(200, 0, 0, 75);
                //diaglinePanel.setBackground(Color.red);
		diaglinePanel.setLocation(120, 75);
		diaglinePanel.setSize(200, 85);
		diaglinePanel.setVisible(true);
		this.add(diaglinePanel);
                JPanel longlinePanel2 = new LinePanel(0, 0, 0, 340);
		longlinePanel2.setLocation(122, 150);
		longlinePanel2.setSize(1, 340);
		longlinePanel2.setVisible(true);
		this.add(longlinePanel2);
                
                viz.setLocation(0,550);
                viz.setSize(800,100);
                viz.setVisible(true);
                this.add(viz);

                viz.setBitsOne(R);
		viz.makeNodesOne();
		viz.repaint();
		validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        expansionTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 700));

        jTextField3.setText(K.toBinaryString());

        jTextField4.setText(R.toBinaryString());

        jTextField5.setText(L.toBinaryString());

        expansionTextField.setText("E");

        jButton1.setText("E");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField8.setText("j8");

        jTextField9.setText("j9");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.setText("j10");

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("S");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("P");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField11.setText("R2");

        jTextField12.setText(R.toBinaryString());

        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText(L.toBinaryString() + R.toBinaryString());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expansionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expansionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        expandedList = DES.permute(R, DES.E_Map);
        expansionTextField.setText(expandedList.toBinaryString());
        viz.setBitsOne(R);
        viz.setBitsTwo(expandedList);
        viz.setMap(DES.E_Map);
        viz.makeNodesOne();
        viz.makeNodesTwo();
        viz.start();
    }                                        


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        BitList temp = expandedList;
        temp.xor(K);
        firstXorList = temp;
        jTextField10.setText(firstXorList.toBinaryString());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sBoxesList = DES.S_Boxes(firstXorList);
        jTextField8.setText(sBoxesList.toBinaryString());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        permutedList = DES.permute(sBoxesList, DES.P_Map);
        jTextField9.setText(permutedList.toBinaryString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BitList temp = permutedList;
        temp.xor(L);
        secondXorList = temp;
        jTextField11.setText(secondXorList.toBinaryString());
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField expansionTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables



private class LinePanel extends JPanel{

        int x1, y1, x2, y2;

		LinePanel(int x1, int y1, int x2, int y2){
                    this.x1 = x1;
                    this.y1 = y1;
                    this.x2 = x2;
                    this.y2 = y2;
			this.setBackground(Color.white);
			this.setPreferredSize(new Dimension(10, 30));
		}


		public void paint(Graphics g) {

			super.paintComponent(g);
			Graphics2D g2d = (Graphics2D)g;

			g2d.drawLine(x1,y1, x2, y2);

		}//end paintcomponent
	}

}
